set(EXECUTABLE_OUTPUT_PATH ${OPT_BIN_DIR})
set(LIBRARY_OUTPUT_PATH    ${OPT_BIN_DIR})


set(OPT_BIN_DIR ${PROJECT_BINARY_DIR}/../bin${PLATFORM})

set(EXECUTABLE_OUTPUT_PATH ${OPT_BIN_DIR})

#needed when dynamic linking
#set(LIBRARY_OUTPUT_PATH    ${OPT_BIN_DIR})
